GET http://127.0.0.1:8000/tasks HTTP/1.1

###

POST http://127.0.0.1:8000/tasks HTTP/1.1
Content-Type: application/json

{
    "title": "post_titlestr 2",
    "description": "post_descriptionstr",
    "categories": ["category_post"],
    "dueDate": "",
    "priority": 1
}

###

DELETE http://127.0.0.1:8000/tasks HTTP/1.1
Content-Type: application/json

{
    "idToDelete": "62528a9cecfc9673898be1f9"
}

###
POST http://127.0.0.1:8000/editTask HTTP/1.1
Content-Type: application/json

{
    "_id": "6252822a762ac780f8cd1236",
    "title": "replacement_title",
    "description": "post_descriptionstr",
    "categories": ["category_post"],
    "dueDate": "",
    "priority": 1
}